Add functions to list library
TroupeLang/Troupe pull request #36
Opened 2024-04-16 10:09 UTC by V-Ask

Added following functions to list library:
contains
filter
first
slice
insert_at_index

2024-05-27 10:16 UTC, aslanix commented on examples/network/bug.zip
should not be in the repo

2024-05-27 10:17 UTC, aslanix commented on examples/network/pingpong/p2ppingpong.trp
this probably need no modifications; maybe move this to another place?

2024-05-27 10:21 UTC, aslanix commented on lib/lists.trp
contains seems to be doing the same as elem that's already in the list

2024-05-27 10:22 UTC, aslanix requested changes
see inline comments

2024-06-03 09:52 UTC, V-Ask reviewed
Unnecessary files removed, and removed contains

2024-08-23 08:23 UTC, merged